version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/libs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/email"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "weekly"