-- =================================================================
-- Adding "organization" better-auth plugin
-- workspace maps to organization, so we need to migrate to owners
-- and we any "pending" workspace_member is an invitation now
-- =================================================================

-- First, remove any duplicate workspace_member records before adding the unique constraint
-- Keep only the most recent record for each workspace_id, user_id combination
DELETE FROM "workspace_member" 
WHERE id NOT IN (
  SELECT DISTINCT ON (workspace_id, user_id) id
  FROM "workspace_member"
  ORDER BY workspace_id, user_id, joined_at DESC
);

-- Now add the unique constraint that will be needed for the upsert
DO $$ BEGIN
 ALTER TABLE "workspace_member" ADD CONSTRAINT "workspace_member_workspace_id_user_id_unique" UNIQUE ("workspace_id", "user_id");
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

-- Create the invitation table
CREATE TABLE IF NOT EXISTS "invitation" (
	"id" text PRIMARY KEY NOT NULL,
	"workspace_id" text NOT NULL,
	"email" text NOT NULL,
	"role" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"expires_at" timestamp NOT NULL,
	"inviter_id" text NOT NULL
);

-- Add foreign key constraints for the invitation table
DO $$ BEGIN
 ALTER TABLE "invitation" ADD CONSTRAINT "invitation_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "invitation" ADD CONSTRAINT "invitation_inviter_id_user_id_fk" FOREIGN KEY ("inviter_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

-- Part A: Migrate existing workspace owners from the `owner_id` column
-- into the `workspace_member` table with the role of "owner".
-- This uses an UPSERT to safely handle cases where the owner might already be a member.
INSERT INTO "workspace_member" (
  id,
  workspace_id,
  user_id,
  role,
  joined_at
)
SELECT
  gen_random_uuid()::text,
  w.id,
  w.owner_id,
  'owner',
  NOW()
FROM
  "workspace" w
WHERE
  w.owner_id IS NOT NULL
ON CONFLICT (workspace_id, user_id) -- If a membership for this user/workspace already exists...
DO UPDATE SET
  role = 'owner'; -- ...just update their role to 'owner'.


-- Part B: Migrate existing "pending" members from the `workspace_member` table
-- into the new `invitation` table before the status column is dropped.
INSERT INTO "invitation" (
  id,
  workspace_id,
  email,
  role,
  status,
  expires_at,
  inviter_id
)
SELECT
  gen_random_uuid()::text,
  wm.workspace_id,
  u.email,
  wm.role,
  'pending',
  NOW() + INTERVAL '1 month', -- Set a default expiration for the new invitation
  -- Find the owner of the workspace to act as the inviter
  (SELECT user_id FROM workspace_member owner WHERE owner.workspace_id = wm.workspace_id AND owner.role = 'owner' LIMIT 1)
FROM
  "workspace_member" wm
JOIN
  "user" u ON wm.user_id = u.id
WHERE
  wm.status = 'pending';


-- =================================================================
-- Step 2: REMAINING SCHEMA CHANGES (Generated by Drizzle)
-- =================================================================
--> statement-breakpoint
ALTER TABLE "session" ADD COLUMN "active_workspace_id" text;
--> statement-breakpoint
ALTER TABLE "workspace" ADD COLUMN "slug" text;
--> statement-breakpoint
ALTER TABLE "workspace" ADD COLUMN "logo" text;
--> statement-breakpoint
ALTER TABLE "workspace" ADD COLUMN "metadata" text;
--> statement-breakpoint
ALTER TABLE "workspace" DROP CONSTRAINT IF EXISTS "workspace_owner_id_user_id_fk";
--> statement-breakpoint
ALTER TABLE "workspace" DROP COLUMN IF EXISTS "owner_id";
--> statement-breakpoint
ALTER TABLE "workspace_member" DROP COLUMN IF EXISTS "status";
--> statement-breakpoint
ALTER TABLE "workspace" ADD CONSTRAINT "workspace_slug_unique" UNIQUE("slug");

-- =================================================================
-- Step 3: TEAM FUNCTIONALITY
-- =================================================================
CREATE TABLE "team_member" (
	"id" text PRIMARY KEY NOT NULL,
	"team_id" text NOT NULL,
	"user_id" text NOT NULL,
	"created_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "team" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"workspace_id" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "invitation" ADD COLUMN "team_id" text;--> statement-breakpoint
ALTER TABLE "session" ADD COLUMN "active_team_id" text;--> statement-breakpoint
ALTER TABLE "team_member" ADD CONSTRAINT "team_member_team_id_team_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_member" ADD CONSTRAINT "team_member_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team" ADD CONSTRAINT "team_workspace_id_workspace_id_fk" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint