services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kaneo
      POSTGRES_USER: kaneo_user
      POSTGRES_PASSWORD: kaneo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaneo_user -d kaneo"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "1337:1337"
    environment:
      - JWT_ACCESS=change-me
      - DATABASE_URL=postgresql://kaneo_user:kaneo_password@postgres:5432/kaneo
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - KANEO_API_URL=http://localhost:1337
    depends_on:
      - api
    restart: unless-stopped

  # Gitea service (optional - enable with --profile gitea)
  gitea-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea_user
      POSTGRES_PASSWORD: gitea_password
    ports:
      - "5433:5432"  # Different port to avoid conflict with main postgres
    volumes:
      - gitea_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitea_user -d gitea"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - gitea

  gitea:
    image: gitea/gitea:1.22
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea_user
      - GITEA__database__PASSWD=gitea_password
      - GITEA__server__ROOT_URL=http://localhost:3000
      - GITEA__server__HTTP_PORT=3000
      - GITEA__webhook__ALLOWED_HOST_LIST=localhost,host.docker.internal
      - GITEA__webhook__SKIP_TLS_VERIFY=true
    restart: unless-stopped
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "2222:22"  # SSH port
    depends_on:
      gitea-postgres:
        condition: service_healthy
    profiles:
      - gitea

volumes:
  postgres_data:
    name: kaneo_postgres_data
  gitea_postgres_data:
    name: gitea_postgres_data
  gitea_data:
    name: gitea_data
