services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: kaneo
      POSTGRES_USER: kaneo_user
      POSTGRES_PASSWORD: kaneo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaneo_user -d kaneo"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "1337:1337"
    environment:
      - JWT_ACCESS=change-me
      - DATABASE_URL=postgresql://kaneo_user:kaneo_password@postgres:5432/kaneo
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - KANEO_API_URL=http://localhost:1337
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
    name: kaneo_postgres_data
