// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/terminology/workspaces.mdx?collection=docs&hash=1745093524530"
import * as docs_8 from "../content/docs/terminology/teams.mdx?collection=docs&hash=1745093524530"
import * as docs_7 from "../content/docs/terminology/tasks.mdx?collection=docs&hash=1745093524530"
import * as docs_6 from "../content/docs/terminology/projects.mdx?collection=docs&hash=1745093524530"
import * as docs_5 from "../content/docs/terminology/index.mdx?collection=docs&hash=1745093524530"
import * as docs_4 from "../content/docs/deployments/traefik.mdx?collection=docs&hash=1745093524530"
import * as docs_3 from "../content/docs/deployments/nginx.mdx?collection=docs&hash=1745093524530"
import * as docs_2 from "../content/docs/deployments/kubernetes.mdx?collection=docs&hash=1745093524530"
import * as docs_1 from "../content/docs/quick-start.mdx?collection=docs&hash=1745093524530"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1745093524530"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"quick-start.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/quick-start.mdx"}, data: docs_1 }, { info: {"path":"deployments/kubernetes.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/deployments/kubernetes.mdx"}, data: docs_2 }, { info: {"path":"deployments/nginx.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/deployments/nginx.mdx"}, data: docs_3 }, { info: {"path":"deployments/traefik.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/deployments/traefik.mdx"}, data: docs_4 }, { info: {"path":"terminology/index.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/terminology/index.mdx"}, data: docs_5 }, { info: {"path":"terminology/projects.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/terminology/projects.mdx"}, data: docs_6 }, { info: {"path":"terminology/tasks.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/terminology/tasks.mdx"}, data: docs_7 }, { info: {"path":"terminology/teams.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/terminology/teams.mdx"}, data: docs_8 }, { info: {"path":"terminology/workspaces.mdx","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/terminology/workspaces.mdx"}, data: docs_9 }], [{"info":{"path":"deployments/meta.json","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/deployments/meta.json"},"data":{"title":"Deployments","pages":["nginx","traefik","kubernetes"],"defaultOpen":true,"icon":"Server"}}, {"info":{"path":"terminology/meta.json","absolutePath":"/home/andrej/projects/kaneo/apps/docs/content/docs/terminology/meta.json"},"data":{"title":"Terminology","pages":["index","workspaces","projects","tasks","teams"],"defaultOpen":true,"icon":"Book"}}])