# API Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaneo.fullname" . }}-api
  labels:
    {{- include "kaneo.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: api
      protocol: TCP
      name: http
  selector:
    {{- include "kaneo.selectorLabels" . | nindent 4 }}

---
# Web Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaneo.fullname" . }}-web
  labels:
    {{- include "kaneo.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: web
      protocol: TCP
      name: http
  selector:
    {{- include "kaneo.selectorLabels" . | nindent 4 }}
