import { timingSafeEqual } from "node:crypto";

// GitLab echoes the hook's secret token back in a plain header rather than
// signing the body the way Gitea does, so delivery is authenticated by
// comparing that token. GitLab 19.0 added a Standard Webhooks signing token in
// `webhook-signature`, but that secret is generated by GitLab and pasted into
// Kaneo, which is the opposite direction from the secret set up here.
export function verifyGitlabToken(
  secret: string,
  tokenHeader: string | undefined,
): boolean {
  if (!tokenHeader || !secret) {
    return false;
  }

  const provided = Buffer.from(tokenHeader, "utf8");
  const expected = Buffer.from(secret, "utf8");

  if (provided.length !== expected.length) {
    return false;
  }

  return timingSafeEqual(provided, expected);
}
