name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request_target: 
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@e0a56afd8846954587b00fff254caf1ec918554e
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: aacevski
          numOfAssignee: 1
